// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxeksaitwgupnzqpoewv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4ZWtzYWl0d2d1cG56cXBvZXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODU3MjQsImV4cCI6MjA2MjI2MTcyNH0.5tySLuFbR-iBjSVfxNKCK9EcITwcU6HcGMENxWpHceU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);